[build]
  command = "pip install -r requirements.txt && streamlit run app.py --server.headless true"
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  PYTHON_VERSION = "3.11"
